server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name rceschel.42.fr www.rceschel.42.fr;

	ssl_certificate		/etc/nginx/certs/rceschel.crt;
	ssl_certificate_key	/etc/nginx/certs/rceschel.key;

	# Set TLS version
	ssl_protocols TLSv1.2 TLSv1.3;
}
