
services:
  nginx:
    env_file: ".env"
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "4343:443"
    volumes:
      - nginx_conf:/etc/nginx/conf.d/:ro

volumes:
  nginx_conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${VOLUMES_HOME}/nginx_conf'

