---
name: inception
---
services:
  nginx:
    environment:
      HOST_DOMAIN: ${HOST_DOMAIN:-login.42.fr}
    container_name: nginx
    build:
      context: ./requirements/nginx/
    volumes:
      - ./requirements/nginx/templates:/etc/nginx/templates:ro
    secrets:
      - source: tls_cert
        target: /run/secrets/${HOST_DOMAIN:-login.42.fr}.crt
      - source: tls_key
        target: /run/secrets/${HOST_DOMAIN:-login.42.fr}.key
    ports:
      - "4343:443"


#configs:
#  nginx_template:
#    file: ./requirements/nginx/templates/default.conf.template

secrets:
  tls_cert:
    file: ./requirements/nginx/certs/${HOST_DOMAIN}.crt
  tls_key:
    file: ./requirements/nginx/certs/${HOST_DOMAIN}.key
