name: inception
services:
  nginx:
    env_file: ".env"
    container_name: nginx
    build:
      context: requirements/nginx/
    volumes:
      - requirements/nginx/templates:/etc/nginx/templates:ro
    secrets:
      - tls_cert
      - tls_key

    ports:
      - "4343:443"

#configs:
#  nginx_template:
#    file: ./requirements/nginx/templates/default.conf.template

secrets:
  tls_cert:
    file: ./requirements/nginx/certs/${BASE_DOMAIN}.crt
  tls_key:
    file: ./requirements/nginx/certs/${BASE_DOMAIN}.key
